### ISSUE TITLE
The blankRow of BS-RSCD dataset

### ISSUE THREAD

**Issue by DelinQu** [zzh-tech/RSCD#4]
Hi,
I'm tring to do an experiment on your dataset but I didn't find readout ratio in dataset dir. Is there a readot or blankRow? Any suggestions would be appreciated! (the box below is the blankRow)
![image](https://user-images.githubusercontent.com/60593268/154475971-22baf7ce-3b24-4ec0-af6a-c973d98b59e8.png)
Thank you in advance! :smile:

**Comment by zzh-tech** [comment]
Hi, the videos were shot at 15fps.
So, the "blankRow" is around 50ms.

**Comment by DelinQu** [comment]
Appreciate it !
