### ISSUE TITLE
Installing requirements

### ISSUE THREAD

**Issue by Magauiya** [zzh-tech/RSCD#6]
Hello, thank you for sharing the code. I could not find meshzoo==0.4.3 version for installation. The oldest pip version is 0.9.11, while a newer version does not support xmin in rectangle.

![image](https://user-images.githubusercontent.com/33094392/199466808-9b025b3a-e3a0-4634-8133-5223223840e1.png)

**Comment by augustelalande** [comment]
https://ftp.unpad.ac.id/pypi/web/simple/meshzoo/

**Comment by Yongzhang-Tan** [comment]
The link is invalid, can you share it again?
